apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  ports:
  - port: 8888
    name: http
    targetPort: 8888
  selector:
    app: jupyter
  type: NodePort

---

apiVersion: v1
kind: Pod
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  containers:
    - name: jupyter
      image: serverless_datascience:dev
      command: ["bash", "-c", "source activate $(cat $ENVIRONMENT | yq -r .name ) &&\
                               jupyter notebook \
                                       --ip=0.0.0.0 \
                                       --NotebookApp.iopub_data_rate_limit=10000000 \
                                       --NotebookApp.token= \
                                       --allow-root"]
      env:
        - name: OPENFAAS_URL
          value: gateway-external.openfaas.svc.cluster.local:8080
      ports:
      - containerPort: 8888
        protocol: TCP
        name: http
      volumeMounts:
        - mountPath: /home/jovyan/work/mnt/
          name: host-mount
        - mountPath: "/var/run/docker.sock"
          name: dockersock
  volumes:
  - name: host-mount
    hostPath:
      path: /mnt
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
