FROM serverless_datascience:base

##
## Install docker in docker
##
RUN curl -fsSL https://get.docker.com -o get-docker.sh &&\
    sh get-docker.sh

##
## Install openfaas cli
##
RUN curl -sL https://cli.openfaas.com | sh

##
## Jupyter extension installation
##
RUN bash -c "\
        source activate $(cat $ENVIRONMENT | yq -r .name );\
	jupyter serverextension enable --py --sys-prefix jupyterlab && \
	jupyter nbextension enable --py --sys-prefix widgetsnbextension && \
	jupyter nbextension enable codefolding/main && \
	jupyter labextension install @pyviz/jupyterlab_pyviz && \
	jupyter labextension install @jupyter-widgets/jupyterlab-manager && \
	jupyter labextension install @jupyterlab/celltags"

##
## Install tini as part of os dependencies
##
ENV TINI_VERSION v0.3.4 
ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini 
RUN chmod +x /tini 

##
## docker run startup
##
RUN usermod -a -G docker $NB_USER
USER root
RUN echo "source activate serverless_datascience" > ~/.bashrc
ENTRYPOINT [ "/tini", "--", "bash", "-c"]
