name: serverless_datascience
dependencies:
- python=3.6.*
- nodejs
- pandas
- openjdk
- maven
- py4j
- ipywidgets
- jupyterlab
- pyzmq
- requests
- beakerx
- ipykernel
- notebook
- pyviz/label/dev::pyviz
- pip
- pip:
    - json2yaml
    - papermill
